services:
  og:
    container_name: og
    image: ghcr.io/ccrsxx/og:latest
    restart: unless-stopped
    ports:
      - '4444:4000'
    env_file:
      - .env
    environment:
      - PORT=4000
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - 'no-new-privileges:true'
