services:
  api:
    container_name: api
    image: ghcr.io/ccrsxx/api:latest
    ports:
      - '${HOST_PORT:-4000}:4000'
    environment:
      - PORT=4000
      - BACKEND_URL=${BACKEND_URL}
      - VALID_ORIGINS=${VALID_ORIGINS}
      - SECRET_KEY=${SECRET_KEY}
      - IPINFO_TOKEN=${IPINFO_TOKEN}
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - JELLYFIN_USERNAME=${JELLYFIN_USERNAME}
      - JELLYFIN_IMAGE_URL=${JELLYFIN_IMAGE_URL}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REFRESH_TOKEN=${SPOTIFY_REFRESH_TOKEN}
      - CLOUDFLARE_CDN_URL=${CLOUDFLARE_CDN_URL}
      - CLOUDFLARE_KV_TOKEN=${CLOUDFLARE_KV_TOKEN}
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_KV_NAMESPACE_ID=${CLOUDFLARE_KV_NAMESPACE_ID}
